export const articles = [
  {
    id: "1",
    image: "/images/i1.avif",
    date: "06/01/25",
    category: "Promotions",
    title: "My Nintendo June Wrap-Up",
    description:
      "My Nintendo is gearing up for the launch of the Nintendo Switch™ 2 system on June 5! As we enter the final lap, let’s check out what’s new in the mon...",
    bannerText: "",
    hasImageBanner: true,
    videoUrl: "https://youtu.be/_ujPFKjIVyo",
    relatedGames: [
      {
        image: "/images/i1.avif",
        title: "Nintendo 64™ – Nintendo Switch Online",
        price: "Free",
        platform: "Nintendo Switch",
      },
      {
        image: "/images/i2.avif",
        title: "Game Boy™ Advance – Nintendo Switch Online",
        price: "Free",
        platform: "Nintendo Switch",
      },
      {
        image: "/images/i3.avif",
        title: "Disney Dreamlight Valley",
        price: "$39.99",
        platform: "Nintendo Switch",
      },
      {
        image: "/images/i4.avif",
        title: "Capcom Fighting Collection 2",
        price: "$39.99",
        platform: "Nintendo Switch",
      },
    ],
  },
  {
    id: "2",
    image: "/images/i2.avif",
    date: "06/01/25",
    category: "Nintendo Switch Online",
    title: "Here’s the latest Nintendo Switch Online news from May!",
    description:
      "Did you know? Active Nintendo Switch Online members have access to a trove of exclusive benefits like playing online in compatible games...",
    bannerText: "MAY UPDATES\nMy Nintendo June Wrap-Up",
    hasImageBanner: true,
    videoUrl: "https://youtu.be/9LmocGJOdZk?si=3sszMJJnHDhZ8MLf",
    relatedGames: [
      {
        image: "/images/i1.avif",
        title: "Nintendo 64™ – Nintendo Switch Online",
        price: "Free",
        platform: "Nintendo Switch",
      },
      {
        image: "/images/i2.avif",
        title: "Game Boy™ Advance – Nintendo Switch Online",
        price: "Free",
        platform: "Nintendo Switch",
      },
    ],
  },
  {
    id: "3",
    image: "/images/i1.avif",
    date: "06/02/25",
    category: "Promotions",
    title: "Super Mario Summer Sale",
    description:
      "Get ready for summer with huge discounts on your favorite Mario games! Don’t miss out on this limited-time offer available until June 15...",
    bannerText: "",
    hasImageBanner: true,
    videoUrl: "",
    relatedGames: [
      {
        image: "/images/i3.avif",
        title: "Disney Dreamlight Valley",
        price: "$39.99",
        platform: "Nintendo Switch",
      },
      {
        image: "/images/i4.avif",
        title: "Capcom Fighting Collection 2",
        price: "$39.99",
        platform: "Nintendo Switch",
      },
    ],
  },
  {
    id: "4",
    image: "/images/i2.avif",
    date: "06/03/25",
    category: "Events",
    title: "Nintendo Direct: Summer 2025",
    description:
      "Join us for the latest Nintendo Direct, where we’ll reveal upcoming games and events for Summer 2025. Tune in on June 10 at 10 AM PST...",
    bannerText: "SUMMER EVENT\nNintendo Direct 2025",
    hasImageBanner: true,
    videoUrl: "",
    relatedGames: [],
  },
  {
    id: "5",
    image: "/images/i3.avif",
    date: "06/04/25",
    category: "Game News",
    title: "New Zelda Game Announced!",
    description:
      "A new Legend of Zelda game has been announced for the Nintendo Switch 2! Get the latest details on this exciting upcoming release...",
    bannerText: "",
    hasImageBanner: true,
    videoUrl: "",
    relatedGames: [],
  },
  {
    id: "6",
    image: "/images/i1.avif",
    date: "06/02/25",
    category: "Promotions",
    title: "Super Mario Summer Sale",
    description:
      "Get ready for summer with huge discounts on your favorite Mario games! Don’t miss out on this limited-time offer available until June 15...",
    bannerText: "",
    hasImageBanner: true,
    videoUrl: "",
    relatedGames: [
      {
        image: "/images/i3.avif",
        title: "Disney Dreamlight Valley",
        price: "$39.99",
        platform: "Nintendo Switch",
      },
      {
        image: "/images/i4.avif",
        title: "Capcom Fighting Collection 2",
        price: "$39.99",
        platform: "Nintendo Switch",
      },
    ],
  },
  {
    id: "7",
    image: "/images/i2.avif",
    date: "06/03/25",
    category: "Events",
    title: "Nintendo Direct: Summer 2025",
    description:
      "Join us for the latest Nintendo Direct, where we’ll reveal upcoming games and events for Summer 2025. Tune in on June 10 at 10 AM PST...",
    bannerText: "SUMMER EVENT\nNintendo Direct 2025",
    hasImageBanner: true,
    videoUrl: "",
    relatedGames: [],
  },
  {
    id: "8",
    image: "/images/i3.avif",
    date: "06/04/25",
    category: "Game News",
    title: "New Zelda Game Announced!",
    description:
      "A new Legend of Zelda game has been announced for the Nintendo Switch 2! Get the latest details on this exciting upcoming release...",
    bannerText: "",
    hasImageBanner: true,
    videoUrl: "",
    relatedGames: [],
  },
  {
    id: "9",
    image: "/images/i4.avif",
    date: "06/02/25",
    category: "Promotions",
    title: "Super Mario Summer Sale",
    description:
      "Get ready for summer with huge discounts on your favorite Mario games! Don’t miss out on this limited-time offer available until June 15...",
    bannerText: "",
    hasImageBanner: true,
    videoUrl: "",
    relatedGames: [
      {
        image: "/images/i3.avif",
        title: "Disney Dreamlight Valley",
        price: "$39.99",
        platform: "Nintendo Switch",
      },
      {
        image: "/images/i4.avif",
        title: "Capcom Fighting Collection 2",
        price: "$39.99",
        platform: "Nintendo Switch",
      },
    ],
  },
  {
    id: "10",
    image: "/images/i4.avif",
    date: "06/03/25",
    category: "Events",
    title: "Nintendo Direct: Summer 2025",
    description:
      "Join us for the latest Nintendo Direct, where we’ll reveal upcoming games and events for Summer 2025. Tune in on June 10 at 10 AM PST...",
    bannerText: "SUMMER EVENT\nNintendo Direct 2025",
    hasImageBanner: true,
    videoUrl: "",
    relatedGames: [],
  },
  {
    id: "11",
    image: "/images/i3.avif",
    date: "06/04/25",
    category: "Game News",
    title: "New Zelda Game Announced!",
    description:
      "A new Legend of Zelda game has been announced for the Nintendo Switch 2! Get the latest details on this exciting upcoming release...",
    bannerText: "",
    hasImageBanner: true,
    videoUrl: "",
    relatedGames: [],
  },
];
